### ISSUE TITLE
Wazuh packages redesign tier 2 - Migrate and adapt Wazuh OVA

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-virtual-machines#1]
## Description 
The Wazuh OVA generation code should be migrated from the `wazuh-packages` repository to this one for 4.9.0.
The repository structure must be defined with this code migration.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/718. Use that issue for additional information and requirements.

## Tasks
- [ ] Migrate the Wazuh OVA generation code into this repository
- [ ] Automate OVA generation through CI using GHA
- [ ] Add secrets to GH (to upload packages to S3)
- [ ] Add CI testing for the Wazuh OVA
- [ ] Upload the Wazuh OVA to S3 through CI
