### ISSUE TITLE
Wazuh dashboard show errors related to SSL in 4.10.0 AMI

### ISSUE THREAD

**Issue by DiegoRatto** [wazuh/wazuh-virtual-machines#116]
## Description
The following log messages have been found in the https://github.com/wazuh/wazuh/issues/26798#issuecomment-2471420823 testing:

```console
Nov 12 12:15:13 wazuh-server opensearch-dashboards[8813]: {"type":"error","@timestamp":"2024-11-12T12:15:13Z","tags":["connection","client","error"],"pid":8813,"level":"error","error":{"message":"140476659615616:error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:\n","name":"Error","stack":"Error: 140476659615616:error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:\n","code":"ERR_SSL_VERSION_TOO_LOW"},"message":"140476659615616:error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:\n"}
```

```console
Nov 13 09:22:38 wazuh-server opensearch-dashboards[997]: {"type":"error","@timestamp":"2024-11-13T09:22:38Z","tags":["connection","client","error"],"pid":997,"level":"error","error":{"message":"139823052822400:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:\n","name":"Error","stack":"Error: 139823052822400:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:\n","code":"ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC"},"message":"139823052822400:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:\n"}
```

```console
Nov 13 09:22:38 wazuh-server opensearch-dashboards[997]: {"type":"error","@timestamp":"2024-11-13T09:22:38Z","tags":["connection","client","error"],"pid":997,"level":"error","error":{"message":"139823052822400:error:141F7065:SSL routines:final_key_share:no suitable key share:../deps/openssl/openssl/ssl/statem/extensions.c:1419:\n","name":"Error","stack":"Error: 139823052822400:error:141F7065:SSL routines:final_key_share:no suitable key share:../deps/openssl/openssl/ssl/statem/extensions.c:1419:\n","code":"ERR_SSL_NO_SUITABLE_KEY_SHARE"},"message":"139823052822400:error:141F7065:SSL routines:final_key_share:no suitable key share:../deps/openssl/openssl/ssl/statem/extensions.c:1419:\n"}
```

```console
Nov 13 09:22:37 wazuh-server opensearch-dashboards[997]: {"type":"error","@timestamp":"2024-11-13T09:22:37Z","tags":["connection","client","error"],"pid":997,"level":"error","error":{"message":"139823052822400:error:140940F4:SSL routines:ssl3_read_bytes:unexpected message:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1496:\n","name":"Error","stack":"Error: 139823052822400:error:140940F4:SSL routines:ssl3_read_bytes:unexpected message:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1496:\n","code":"ERR_SSL_UNEXPECTED_MESSAGE"},"message":"139823052822400:error:140940F4:SSL routines:ssl3_read_bytes:unexpected message:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1496:\n"}
```

```console
Nov 13 09:38:20 wazuh-server opensearch-dashboards[997]: {"type":"error","@timestamp":"2024-11-13T09:38:20Z","tags":["connection","client","error"],"pid":997,"level":"error","error":{"message":"TLS session renegotiation attack detected","name":"Error","stack":"Error [ERR_TLS_SESSION_ATTACK]: TLS session renegotiation attack detected\n    at new NodeError (internal/errors.js:322:7)\n    at TLSWrap.onhandshakestart (_tls_wrap.js:129:25)","code":"ERR_TLS_SESSION_ATTACK"},"message":"TLS session renegotiation attack detected"}
```

There are some similar errors reported at https://github.com/wazuh/wazuh-packages/issues/2106, https://github.com/wazuh/wazuh-packages/issues/2326 and https://github.com/wazuh/wazuh-packages/issues/2445 , but they are not the same.

## Tasks

- [x] Analyze each message obtained (OVA/AMI)
- [x] Open an issue for each error and apply the necessary fix if necessary

## Validation

- [ ] The OVA/AMI are built without these error messages or it is validated that they can show them

**Comment by Enaraque** [comment]
# Update report

After creating an instance with the 4.10.0 AMI in AWS and accessing the dashboard, the reported error logs were not retrieved. The only error message displayed was the following:

```console
nov 14 11:41:51 wazuh-server opensearch-dashboards[8640]: {"type":"error","@timestamp":"2024-11-14T11:41:51Z","tags":["connection","client","error"],"pid":8640,"level":"error","error":{"message":"140402367256448:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1563:SSL alert number 46\n","name":"Error","stack":"Error: 140402367256448:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1563:SSL alert number 46\n","code":"ERR_SSL_SSLV3_ALERT_CERTIFICATE_UNKNOWN"},"message":"140402367256448:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1563:SSL alert number 46\n"}
```

The certificates have been regenerated to see if this could resolve the error, but it persists. This may be due to the type of certificate we are using, which is self-signed and not signed by an authorized CA.

The same error was also discussed here: https://github.com/wazuh/wazuh-packages/issues/2106
