### ISSUE TITLE
Change OVA OS to AL2023

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-virtual-machines#122]
## Description
We need to change the OVA OS to AL2023

## Tasks
- [x] Generate an AL2023 box to be used for the OVA
- [x] Upload the box to S3
- [ ] Test the OVA build using the new box with the pipeline
- [ ] Validate the new OVA works.

NOTE: the tests can be made using the 4.8.0 packages.
