### ISSUE TITLE
Migrate the OVA related files to `wazuh-virtual-machines`

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-virtual-machines#19]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the OVA-related files from the `wazuh-packages` repository to this one.

## Tasks
- [x] Migrate all the OVA related files from  the `wazuh-packages` repository to this one
- [x] Validate the OVA can be built locally after the migration
- [x] Remove OVA related files from the `wazuh-packages` repository 

## Related
- https://github.com/wazuh/wazuh-virtual-machines/issues/22
