### ISSUE TITLE
Wazuh packages redesign tier 2 - Migrate and adapt Wazuh AMI

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-virtual-machines#2]
## Description 
The Wazuh AMI generation code should be migrated to this repository for 4.9.0.
The repository structure must be defined with this code migration.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/718. Use that issue for additional information and requirements.

## Tasks
- [ ] Migrate the Wazuh AMI generation code into this repository
- [ ] Automate the Wazuh AMI generation through CI using GHA
- [ ] Add secrets to GH (to upload packages to S3)
- [ ] Add CI testing for the Wazuh AMI
- [ ] Upload the Wazuh AMI to S3 through CI
