### ISSUE TITLE
Migrate the `Packages_Builder_OVA` pipeline to GHA

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-virtual-machines#20]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the `Packages_Builder_OVA` pipeline from Jenkins to GHA.

## Tasks
- [x] Replicate the `Packages_Builder_OVA` pipeline in GHA
- [x] The GHA should allow the following parameters:
    - PACKAGE_VERSION
    - VIRTUAL_MACHINES_REFERENCE
    - FILEBEAT_VERSION
    - S3_BUCKET
    - PACKAGES_REPOSITORY
    - S3_REPOSITORY
- [x] The GHA should allow to be executed on demand
- [x] Validate the OVA generated by the GHA works

## Related
- https://github.com/wazuh/wazuh-virtual-machines/issues/22
