### ISSUE TITLE
Support new stage RC 1 for 4.8.2 in wazuh-virtual-machines repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-virtual-machines#25]
## Description

This issue attempts to support a new stage RC 1 for 4.8.2 in the wazuh-virtual-machines repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.2 (if applicable).
- [ ] Bump revision for branch 4.8.2 on wazuh-virtual-machines repository.
- [ ] Create tag v4.8.2-rc1 from branch 4.8.2 on wazuh-virtual-machines repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-virtual-machines/releases/tag/v4.8.2-rc1.
