### ISSUE TITLE
Modify the provisioning scripts in OVA with the changes applied in the Wazuh installation assistant

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-virtual-machines#47]
related: https://github.com/wazuh/wazuh-installation-assistant/issues/63

Regarding the issue, the installation assistant allows you to choose by parameter from which repository you want to install the packages.

https://github.com/wazuh/wazuh-virtual-machines/blob/192030f2b6388b143916b1204dfed02c3873773b/ova/generate_ova.sh#L232-L238

https://github.com/wazuh/wazuh-virtual-machines/blob/192030f2b6388b143916b1204dfed02c3873773b/ova/generate_ova.sh#L256

## Tasks

- [x] Test OVA local build
- [x] Update Workflow and Workflow script to the new logic
- [x] Remove `WAZUH_VIRTUAL_MACHINES_REFERENCE` input
- [x] Remove `S3_REPOSITORY` input
- [x] Create a new input, `OVA_REVISION`
- [x] Add a new parameter for `It's stage`, for build stage OVA. Reference: https://github.com/wazuh/wazuh-puppet/blob/3b0ccd21ce9f853b7a24e96a7c00f55c324752da/.github/workflows/Puppet_module_builder.yml#L11C1-L14C23
- [x] Test Build OVA workflow
- [x] Update `S3_BUCKET` variable with `packages-dev.internal.wazuh.com`
- [x] Upload OVA to packages-dev.internal.wazuh.com/development/wazuh/4.x/secondary/OVA

> [!IMPORTANT]
> The OVA package must have this format wazuh-4.x.x-revision.ova 
> For stage package must have a numeric revision, for example: `wazuh-4.10.0-2.ova`
> For development package must have revision equal to 0 and commit associate, for example: `wazuh-4.10.0-0-f45asg.ova`

https://github.com/wazuh/wazuh-virtual-machines/blob/192030f2b6388b143916b1204dfed02c3873773b/.github/workflows/ansible_playbooks/ova_generator.yaml#L34-L41
