### ISSUE TITLE
Modify the provisioning scripts in AMI with the changes applied in the Wazuh installation assistant

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-virtual-machines#48]
related: https://github.com/wazuh/wazuh-installation-assistant/issues/63

Regarding the issue, the installation assistant allows you to choose by parameter from which repository you want to install the packages.

https://github.com/wazuh/wazuh-virtual-machines/blob/192030f2b6388b143916b1204dfed02c3873773b/ova/generate_ova.sh#L232-L238

https://github.com/wazuh/wazuh-virtual-machines/blob/192030f2b6388b143916b1204dfed02c3873773b/ova/generate_ova.sh#L256

## Tasks
- [x] Update Workflow and Workflow script to the new logic
- [x] Remove WAZUH_VIRTUAL_MACHINES_REFERENCE input
- [x] Change `SUFFIX_AMI` input to `AMI_REVISION`
- [x] Test Build AMI workflow

> [!IMPORTANT]
> The AMI_REVISION input must have a numeric format like `wazuh-4.10.0-1` it is reserved for AMI candidates, to build a development AMI use another revision format, like -dev
