### ISSUE TITLE
Support new stage Alpha 1 for 4.10.0 in wazuh-virtual-machines repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-virtual-machines#51]
## Description

This issue attempts to support a new stage Alpha 1 for 4.10.0 in the wazuh-virtual-machines repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [ ] ~~Bump revision for branch 4.10.0 on wazuh-virtual-machines repository.~~
- [x] Create tag v4.10.0-alpha1 from branch 4.10.0 on wazuh-virtual-machines repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-virtual-machines/releases/tag/v4.10.0-alpha1.
